package org.fabric3.samples.bigbank.client.ws.loan;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 */
@WebServiceClient(name = "LoanServiceService",
                  targetNamespace = "http://loan.api.bigbank.samples.fabric3.org/",
                  wsdlLocation = "http://localhost:8181/loanService?wsdl")
public class LoanServiceService
        extends Service {

    private final static URL LOANSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.fabric3.samples.bigbank.client.ws.loan.LoanServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.fabric3.samples.bigbank.client.ws.loan.LoanServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8181/loanService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8181/loanService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOANSERVICESERVICE_WSDL_LOCATION = url;
    }

    public LoanServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanServiceService() {
        super(LOANSERVICESERVICE_WSDL_LOCATION, new QName("http://loan.api.bigbank.samples.fabric3.org/", "LoanServiceService"));
    }

    /**
     * @return returns LoanService
     */
    @WebEndpoint(name = "LoanServicePort")
    public LoanService getLoanServicePort() {
        return super.getPort(new QName("http://loan.api.bigbank.samples.fabric3.org/", "LoanServicePort"), LoanService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the
     *                 <code>features</code> parameter will have their default values.
     * @return returns LoanService
     */
    @WebEndpoint(name = "LoanServicePort")
    public LoanService getLoanServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://loan.api.bigbank.samples.fabric3.org/", "LoanServicePort"), LoanService.class, features);
    }

}
