
package org.fabric3.samples.ws.calculator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalculatorServiceService", targetNamespace = "http://calculator.ws.samples.fabric3.org/", wsdlLocation = "http://localhost:8181/calculator?wsdl")
public class CalculatorServiceService
    extends Service
{

    private final static URL CALCULATORSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.fabric3.samples.ws.calculator.CalculatorServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.fabric3.samples.ws.calculator.CalculatorServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8181/calculator?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8181/calculator?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALCULATORSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CalculatorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServiceService() {
        super(CALCULATORSERVICESERVICE_WSDL_LOCATION, new QName("http://calculator.ws.samples.fabric3.org/", "CalculatorServiceService"));
    }

    /**
     * 
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort() {
        return super.getPort(new QName("http://calculator.ws.samples.fabric3.org/", "CalculatorServicePort"), CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calculator.ws.samples.fabric3.org/", "CalculatorServicePort"), CalculatorService.class, features);
    }

}
