package org.fabric3.samples.ws.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 */
@WebService(name = "CalculatorService", targetNamespace = "http://calculator.ws.samples.fabric3.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface CalculatorService {


    /**
     * @param arg1
     * @param arg0
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add",
                    targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                    className = "org.fabric3.samples.ws.calculator.Add")
    @ResponseWrapper(localName = "addResponse",
                     targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                     className = "org.fabric3.samples.ws.calculator.AddResponse")
    public double add(
            @WebParam(name = "arg0", targetNamespace = "")
            double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            double arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract",
                    targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                    className = "org.fabric3.samples.ws.calculator.Subtract")
    @ResponseWrapper(localName = "subtractResponse",
                     targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                     className = "org.fabric3.samples.ws.calculator.SubtractResponse")
    public double subtract(
            @WebParam(name = "arg0", targetNamespace = "")
            double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            double arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply",
                    targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                    className = "org.fabric3.samples.ws.calculator.Multiply")
    @ResponseWrapper(localName = "multiplyResponse",
                     targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                     className = "org.fabric3.samples.ws.calculator.MultiplyResponse")
    public double multiply(
            @WebParam(name = "arg0", targetNamespace = "")
            double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            double arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide",
                    targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                    className = "org.fabric3.samples.ws.calculator.Divide")
    @ResponseWrapper(localName = "divideResponse",
                     targetNamespace = "http://calculator.ws.samples.fabric3.org/",
                     className = "org.fabric3.samples.ws.calculator.DivideResponse")
    public double divide(
            @WebParam(name = "arg0", targetNamespace = "")
            double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            double arg1);

}
